"""Initial schema: sources, articles, sentences

Revision ID: 0001
Revises:
Create Date: 2026-02-23

IMPORTANT: This migration is hand-written — do NOT replace with autogenerated output.
Alembic autogenerate cannot produce GENERATED ALWAYS AS STORED syntax for tsvector
columns, and produces false-positive drift detection on the GIN index. This migration
is the ground truth for the schema.
"""
from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create sources table first (articles FK references it)
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("feed_url", sa.Text(), nullable=False, unique=True),
    )

    # Create articles table (without search_vector — added via raw SQL below)
    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("url_hash", sa.String(64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_id", sa.Integer(), sa.ForeignKey("sources.id"), nullable=True),
    )

    # url_hash unique constraint for deduplication (sha256 hex of normalized URL)
    op.create_unique_constraint("uq_articles_url_hash", "articles", ["url_hash"])

    # GENERATED ALWAYS AS STORED column — must be added via raw SQL.
    # SQLAlchemy op.add_column cannot express GENERATED ALWAYS AS syntax.
    # PostgreSQL computes and maintains this column automatically on every INSERT/UPDATE.
    op.execute("""
        ALTER TABLE articles
        ADD COLUMN search_vector tsvector
        GENERATED ALWAYS AS (
            to_tsvector('english', coalesce(title, '') || ' ' || coalesce(body, ''))
        ) STORED
    """)

    # GIN index on the generated tsvector column — enables full-text search.
    # Must be created in migration zero (not retrofitted) to avoid table lock on large tables.
    # This index is excluded from Alembic autogenerate comparison by name in env.py.
    op.execute("""
        CREATE INDEX ix_articles_search_vector ON articles USING GIN (search_vector)
    """)

    # Create sentences table — child of articles, not a JSON column.
    # ondelete CASCADE ensures sentences are deleted when parent article is deleted.
    op.create_table(
        "sentences",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "article_id",
            sa.Integer(),
            sa.ForeignKey("articles.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("label", sa.String(20), nullable=True),   # fact/opinion/mixed/unclear
        sa.Column("confidence", sa.Float(), nullable=True),  # 0.0 - 1.0
    )
    # Index on article_id for efficient per-article sentence queries
    op.create_index("ix_sentences_article_id", "sentences", ["article_id"])


def downgrade() -> None:
    op.drop_table("sentences")
    op.drop_index("ix_articles_search_vector", table_name="articles")
    op.drop_table("articles")
    op.drop_table("sources")
