"""add_language_column

Revision ID: 1ad44a3e4f6d
Revises: cd9dc34cc250
Create Date: 2026-03-03 15:26:53.602435

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ad44a3e4f6d"
down_revision: Union[str, Sequence[str], None] = "cd9dc34cc250"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles", sa.Column("language", sa.String(length=10), nullable=True)
    )
    op.add_column("sources", sa.Column("language", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sources", "language")
    op.drop_column("articles", "language")
    # ### end Alembic commands ###
