"""Add country_code and region to sources

Revision ID: 328bf7f88503
Revises: 72fa28203e8d
Create Date: 2026-03-02 09:13:27.995793

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "328bf7f88503"
down_revision: Union[str, Sequence[str], None] = "72fa28203e8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sources", sa.Column("country_code", sa.String(length=2), nullable=True)
    )
    op.add_column("sources", sa.Column("region", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sources", "region")
    op.drop_column("sources", "country_code")
    # ### end Alembic commands ###
