"""

Revision ID: 72fa28203e8d
Revises: 0003
Create Date: 2026-03-01 23:34:44.270299

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72fa28203e8d"
down_revision: Union[str, Sequence[str], None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "article_id", "language", name="uq_translations_article_language"
        ),
    )
    # op.create_index('ix_articles_search_vector', 'articles', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_index(op.f("ix_sentences_article_id"), table_name="sentences")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_sentences_article_id"), "sentences", ["article_id"], unique=False
    )
    # op.drop_index('ix_articles_search_vector', table_name='articles', postgresql_using='gin')
    op.drop_table("translations")
    # ### end Alembic commands ###
