"""add_sentences_data_to_translation

Revision ID: cd9dc34cc250
Revises: 328bf7f88503
Create Date: 2026-03-02 23:07:46.540308

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd9dc34cc250"
down_revision: Union[str, Sequence[str], None] = "328bf7f88503"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("translations", sa.Column("sentences_data", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("translations", "sentences_data")
    # ### end Alembic commands ###
