"""Source definitions for all target RSS feeds."""

# Each source is stored in the database via seed_sources() on startup.
# The feed_url values here are the initial seeds; they can be updated in the
# database without a code change.

SOURCES = [
    {
        "name": "BBC News",
        "feed_url": "http://feeds.bbci.co.uk/news/rss.xml",
        "country_code": "GB",
        "region": "Europe",
        "language": "en",
    },
    {
        "name": "Reuters",
        "feed_url": "https://www.reuters.com/arc/outboundfeeds/news-sitemap-index/?outputType=xml",
        "country_code": "GB",
        "region": "Europe",
        "language": "en",
    },
    {
        "name": "AP News",
        "feed_url": "https://rsshub.app/apnews/topics/apf-topnews",
        "country_code": "US",
        "region": "North America",
        "language": "en",
    },
    {
        "name": "NPR",
        "feed_url": "https://feeds.npr.org/1001/rss.xml",
        "country_code": "US",
        "region": "North America",
        "language": "en",
    },
    {
        "name": "The Guardian",
        "feed_url": "https://www.theguardian.com/world/rss",
        "country_code": "GB",
        "region": "Europe",
        "language": "en",
    },
    {
        "name": "Deutsche Welle",
        "feed_url": "https://rss.dw.com/xml/rss-de-all",
        "country_code": "DE",
        "region": "Europe",
        "language": "de",
    },
    {
        "name": "France 24",
        "feed_url": "https://www.france24.com/fr/rss",
        "country_code": "FR",
        "region": "Europe",
        "language": "fr",
    },
    {
        "name": "El País",
        "feed_url": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
        "country_code": "ES",
        "region": "Europe",
        "language": "es",
    },
    {
        "name": "NHK News",
        "feed_url": "https://www.nhk.or.jp/rss/news/cat0.xml",
        "country_code": "JP",
        "region": "Asia",
        "language": "ja",
    },
    {
        "name": "The Hindu",
        "feed_url": "https://www.thehindu.com/news/national/feeder/default.rss",
        "country_code": "IN",
        "region": "Asia",
        "language": "en",
    },
    {
        "name": "SCMP",
        "feed_url": "https://www.scmp.com/rss/91/feed",
        "country_code": "HK",
        "region": "Asia",
        "language": "en",
    },
    {
        "name": "Al Jazeera Arabic",
        "feed_url": "https://www.aljazeera.net/aljazeerarss/a7c186be-1baa-4bd4-9d80-a84db769f779/73d0e1b4-532f-45ef-b135-bfdff8b8cab9",
        "country_code": "QA",
        "region": "Middle East",
        "language": "ar",
    },
    {
        "name": "El País Uruguay",
        "feed_url": "https://www.elpais.com.uy/rss/",
        "country_code": "UY",
        "region": "South America",
        "language": "es",
    },
    {
        "name": "News24",
        "feed_url": "http://feeds.news24.com/articles/news24/TopStories/rss",
        "country_code": "ZA",
        "region": "Africa",
        "language": "en",
    },
    {
        "name": "Meduza",
        "feed_url": "https://meduza.io/rss/all",
        "country_code": "LV",
        "region": "Europe",
        "language": "ru",
    },
    {
        "name": "TASS",
        "feed_url": "https://tass.ru/rss/v2.xml",
        "country_code": "RU",
        "region": "Europe",
        "language": "ru",
    },
    {
        "name": "CBC News",
        "feed_url": "https://www.cbc.ca/cmlink/rss-topstories",
        "country_code": "CA",
        "region": "North America",
        "language": "en",
    },
    {
        "name": "Sermitsiaq",
        "feed_url": "https://sermitsiaq.ag/rss",
        "country_code": "GL",
        "region": "North America",
        "language": "da",
    },
    {
        "name": "SVT Nyheter",
        "feed_url": "https://www.svt.se/nyheter/rss.xml",
        "country_code": "SE",
        "region": "Europe",
        "language": "sv",
    },
    {
        "name": "G1",
        "feed_url": "https://g1.globo.com/rss/g1/",
        "country_code": "BR",
        "region": "South America",
        "language": "pt",
    },
    {
        "name": "Kazinform",
        "feed_url": "https://www.inform.kz/kz/rss",
        "country_code": "KZ",
        "region": "Asia",
        "language": "kk",
    },
    {
        "name": "Montsame",
        "feed_url": "https://montsame.mn/mn/rss",
        "country_code": "MN",
        "region": "Asia",
        "language": "mn",
    },
    {
        "name": "Xinhua",
        "feed_url": "https://rsshub.app/xinhua/world",
        "country_code": "CN",
        "region": "Asia",
        "language": "zh",
    },
    {
        "name": "ABC News",
        "feed_url": "https://www.abc.net.au/news/feed/51120/rss.xml",
        "country_code": "AU",
        "region": "Oceania",
        "language": "en",
    },
    {
        "name": "El Universal",
        "feed_url": "https://www.eluniversal.com.mx/rss.xml",
        "country_code": "MX",
        "region": "North America",
        "language": "es",
    },
    {
        "name": "Clarín",
        "feed_url": "https://www.clarin.com/rss/lo-ultimo/",
        "country_code": "AR",
        "region": "South America",
        "language": "es",
    },
    {
        "name": "El Tiempo",
        "feed_url": "https://www.eltiempo.com/rss/mundo.xml",
        "country_code": "CO",
        "region": "South America",
        "language": "es",
    },
    {
        "name": "Punch",
        "feed_url": "https://punchng.com/feed/",
        "country_code": "NG",
        "region": "Africa",
        "language": "en",
    },
    {
        "name": "The Star Kenya",
        "feed_url": "https://www.the-star.co.ke/rss",
        "country_code": "KE",
        "region": "Africa",
        "language": "en",
    },
    {
        "name": "Al Ahram",
        "feed_url": "https://gate.ahram.org.eg/NewsRss.aspx",
        "country_code": "EG",
        "region": "Africa",
        "language": "ar",
    },
    {
        "name": "TRT Haber",
        "feed_url": "https://www.trt.net.tr/rss/manset.rss",
        "country_code": "TR",
        "region": "Middle East",
        "language": "tr",
    },
    {
        "name": "Al Arabiya",
        "feed_url": "https://www.alarabiya.net/.mrss/ar/latest-news.xml",
        "country_code": "SA",
        "region": "Middle East",
        "language": "ar",
    },
    {
        "name": "Ynet",
        "feed_url": "http://www.ynet.co.il/Integration/StoryRss2.xml",
        "country_code": "IL",
        "region": "Middle East",
        "language": "he",
    },
    {
        "name": "Mehr News",
        "feed_url": "https://www.mehrnews.com/rss",
        "country_code": "IR",
        "region": "Middle East",
        "language": "fa",
    },
    {
        "name": "Express News",
        "feed_url": "https://www.express.pk/feed/",
        "country_code": "PK",
        "region": "Asia",
        "language": "ur",
    },
    {
        "name": "Kompas",
        "feed_url": "https://sindikasi.kompas.com/rs/baca/nasional",
        "country_code": "ID",
        "region": "Asia",
        "language": "id",
    },
    {
        "name": "Thairath",
        "feed_url": "https://www.thairath.co.th/rss/news",
        "country_code": "TH",
        "region": "Asia",
        "language": "th",
    },
    {
        "name": "Yonhap",
        "feed_url": "https://www.yna.co.kr/rss/news.xml",
        "country_code": "KR",
        "region": "Asia",
        "language": "ko",
    },
    {
        "name": "VNExpress",
        "feed_url": "https://vnexpress.net/rss/tin-moi-nhat.rss",
        "country_code": "VN",
        "region": "Asia",
        "language": "vi",
    },
    {
        "name": "Inquirer",
        "feed_url": "https://www.inquirer.net/fullfeed/",
        "country_code": "PH",
        "region": "Asia",
        "language": "en",
    },
    {
        "name": "ANSA",
        "feed_url": "https://www.ansa.it/sito/ansait_rss.xml",
        "country_code": "IT",
        "region": "Europe",
        "language": "it",
    },
    {
        "name": "Ukrainska Pravda",
        "feed_url": "https://www.pravda.com.ua/rss/",
        "country_code": "UA",
        "region": "Europe",
        "language": "uk",
    },
    {
        "name": "RNZ",
        "feed_url": "https://www.rnz.co.nz/rss/news.xml",
        "country_code": "NZ",
        "region": "Oceania",
        "language": "en",
    },
]
